# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf829c0fece524e91f9832c1d641975b9bf9195a2a6e443574cc1380a5ad0e3701ceee13a94c7961495269ee881a4a71cb106b025b16ba03942fa3259df2f939

test:
  secret_key_base: f18f05a11b04390b26a47c99d056742958f44a0a6ac7059f75473d459b4d64e33085b3d118f732b15d3d259cad7b1a9263fd858beee2a160b01e6255b535ea72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
